### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Strahilchu** [RoinujNosde/CryptoMarket#10]
[12:00:59 WARN]: [CryptoMarket] Plugin CryptoMarket v2.1.0 generated an exception while executing task 2683595
java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:167) ~[?:?]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:?]
        at net.epconsortium.cryptomarket.util.Configuration.isValid(Configuration.java:194) ~[CryptoMarket-2.1.0.jar:?]
        at net.epconsortium.cryptomarket.util.Configuration.lambda$getCoins$0(Configuration.java:174) ~[CryptoMarket-2.1.0.jar:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at net.epconsortium.cryptomarket.util.Configuration.getCoins(Configuration.java:174) ~[CryptoMarket-2.1.0.jar:?]
        at net.epconsortium.cryptomarket.finances.ExchangeRates$1.run(ExchangeRates.java:75) ~[CryptoMarket-2.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-76]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Airplane-76]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Airplane-76]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Strahilchu** [comment]
Plugin and server version are included in that console error but if you need more information let me know :)

**Comment by RoinujNosde** [comment]
It seems the plugin can't find the digital_currency_list.csv file inside the jar.
Did you delete it?

And 2.1.1 is out, which fixes some bugs.

**Comment by Strahilchu** [comment]
My bad! I thought I had it updated xD
